name = 'Obsession'
license = 'MIT'
licenselink = 'https://github.com/shubhamoli/obsession/blob/master/LICENSE.md'
description = 'Obsession - Obsidian look-alike theme for Hugo'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/shubhamoli/obsession'

# If you have a running demo of the theme
demosite = 'https://nakli.tech'

# Taxonomy terms
tags = ['blog', 'notes', 'obsidian']
features = []

# If the theme has a single author
[author]
  name = 'Shubham Oli'
  homepage = 'https://nakli.tech'
